dist: xenial

language: node_js
node_js:
- "10"

# Install specific version
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
- export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn install --non-interactive

script:
#- yarn test --verbose
- yarn run build

# Monitor only these branches
branches:
  only:
  - master
  - dev

# $HOME/.cache/yarn
cache:
  yarn: true

# https://docs.travis-ci.com/user/deployment/pages/
before_deploy:
- npm run docs
- echo '# Live examples' > docs/README.md

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  target-branch:  'gh-pages'
  local-dir:  'docs'
  on:
    branch: 'master'
